config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  resources :pages, only: :index

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :winner, class_name: 'User', optional: true
  has_many :matchups
  has_many :players, through: :matchups, source: :user

  X_COORDINATES = %w(a b c d e f g h i j k l m n o p q r s t u v w x y z).freeze
  Y_COORDINATES = %w(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25).freeze

  enum status: { waiting_opponent: 0, in_progress: 1, finished: 2, canceled: 9 }

  validates :title, :size, presence: true

  after_initialize :set_defaults

  scope :free, -> { where(rating: false) }
  scope :rating, -> { where(rating: true) }
  scope :active, -> { where(status: [:waiting_opponent, :in_progress]) }

  def set_defaults
    self.cell_size = self.class.cell_size(size)
    self.cells = self.class.cells_for(size)
    self.win_list = self.class.win_list_for(size)
  end

  class << self

    def cell_size(size)
      case size
      when 0..7 then 12
      when 7..10 then 8
      when 10..20 then 5
      else 4
      end
    end

    def cells_for(size)
      X_COORDINATES[0...size].map do |x|
        Y_COORDINATES[0...size].map do |y|
          "#{x}-#{y}"
        end
      end
    end

    def possible_combinations_for(size)
      size * (size - 4) * 2 + 2*(size - 4)**2
    end

    def win_list_for(size)
      cells = cells_for(size)

      cols = cells.flat_map do |col|
        col.each_cons(5).to_a
      end

      rows = cells.transpose.flat_map do |col|
        col.each_cons(5).to_a
      end

      main_diag = (0...size).map.with_index do |step, index|
        "#{X_COORDINATES[step]}-#{Y_COORDINATES[index]}"
      end

      main_diag_rev = (0...size).to_a.reverse.map.with_index do |step, index|
        "#{X_COORDINATES[step]}-#{Y_COORDINATES[index]}"
      end

      add_diags = []

      (size - 5).times do |s|
        offcet = s + 1
        add_diags << (0...(size - offcet)).map.with_index do |step, index|
          "#{X_COORDINATES[step]}-#{Y_COORDINATES[index + offcet]}"
        end
        add_diags << (0...(size - offcet)).map.with_index do |step, index|
          "#{X_COORDINATES[step + offcet]}-#{Y_COORDINATES[index]}"
        end
        add_diags << (0...(size - offcet)).to_a.reverse.map.with_index do |step, index|
          "#{X_COORDINATES[step]}-#{Y_COORDINATES[index]}"
        end
        add_diags << (0...(size - offcet)).to_a.reverse.map.with_index do |step, index|
          "#{X_COORDINATES[step + offcet]}-#{Y_COORDINATES[index + offcet]}"
        end
      end

      diags = [main_diag, main_diag_rev, *add_diags].flat_map do |col|
        col.each_cons(5).to_a
      end

      [*rows, *cols, *diags]
    end
  end
end

app/models/matchup.rb
class Matchup < ApplicationRecord
  belongs_to :game
  belongs_to :user

  enum mark: { x: 0, o: 1 }

  before_create :seed

  def seed
    if game.matchups.size == 1
      self.mark = self.class.marks.keys.sample
    else
      self.mark = game.matchups.first.mark == :x ? :o : :x
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :matchups
  has_many :games, through: :matchups

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_action_cable_identifier

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private

  def set_action_cable_identifier
    cookies.encrypted[:session_id] = session.id.to_s
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # TODO: implement restore game after reload
    # @game = current_game
  end

  private

  def current_game
    (current_user && current_user.games.active.last) || Rails.cache.fetch("game:#{session.id}:active")
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :html, :json
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :html, :json
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Tictactoeadv
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.overflow-hidden.min-h-screen.bg-gray-300.font-sans
    = yield

app/views/pages/_login.html.slim
- if errors
  .flex.flex-wrap.h-full.items-center
    .text-center.w-full.text-red-600
      | Hey, something went wrong!
    .text-center.w-full.text-red-600
      = errors
- elsif user
  = form_with(model: @current_user, url: destroy_session_path(user), html: {role: 'form', class: 'h-full', attr: 'data-reflex-permanent', method: :delete}, data: { type: :json, action: 'ajax:success->login#logout' }) do |f|
    .flex.flex-wrap.h-full.items-center
      .flex.flex-row.justify-around.w-full
        .self-center
          | Hello,
          | &nbsp;
          = user.name
          | !
      .flex.flex-row.justify-center.w-full
        .self-center
          = f.submit 'logout', class: 'px-2 py-1 rounded-sm bg-blue-300'
- elsif login
  = form_with(model: User.new, url: session_path(:user), html: {role: 'form', class: 'h-full'}, data: { type: :json, action: 'ajax:success->login#success ajax:error->login#failure' }) do |f|
    .flex.flex-wrap.h-full.items-center
      .flex.flex-row.justify-around.w-full
        .self-center
          = f.text_field :email, placeholder: 'email', id: 'header_user_email', class: 'p-1'
        .self-center
          = f.password_field :password, placeholder: 'password', id: 'header_user_password', class: 'p-1'
      .flex.flex-row.justify-center.w-full
        .self-center
          = f.submit 'login', class: 'px-2 py-1 rounded-sm bg-green-300'
      .flex.flex-row.justify-around.w-full
        .self-center
          | Not registered yet?
          | &nbsp;
          a.text-blue-500 href='#' data-reflex='click->Login#toggle' data-login=login
            | Sing up!
- else
  = form_with(model: User.new, url: registration_path(:user), html: {role: 'form', class: 'h-full'}, data: { type: :json, action: 'ajax:success->login#success ajax:error->login#failure' }) do |f|
    .flex.flex-wrap.h-full.items-center
      .flex.flex-row.justify-around.w-full
        .self-center
          = f.email_field :email, autofocus: true, placeholder: 'email', class: 'p-1'
        .self-center
          = f.text_field :name, placeholder: 'name', class: 'p-1'
      .flex.flex-row.justify-around.w-full
        .self-center
          = f.password_field :password, autocomplete: 'off', placeholder: 'password', class: 'p-1'
        .self-center
          = f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'password confirmation', class: 'p-1'
      .flex.flex-row.justify-center.w-full
        .self-center
          = f.submit 'Sign up', class: 'px-2 py-1 rounded-sm bg-green-300'
      .flex.flex-row.justify-center.w-full
        .self-center
          | Already have login?
          | &nbsp;
          a.text-blue-500 href='#' data-reflex='click->Login#toggle' data-login=login
            | Sing in!

app/views/pages/index.html.slim
.z-0.m-1.h-screen.grid.grid-rows-5.grid-cols-5.gap-1 data-controller='game login'
  div.bg-gray-100.rounded-sm.col-start-1.col-end-2.row-start-1.row-end-2
    |
  #login.bg-gray-100.rounded-sm.col-start-2.col-end-5.row-start-1.row-end-2 data-reflex-root='#login'
    = render 'login', login: @login, user: current_user, errors: @errors
  div.bg-gray-100.rounded-sm.col-start-5.col-end-6.row-start-1.row-end-2
    |
  div.bg-gray-100.rounded-sm.col-start-1.col-end-2.row-start-2.row-end-5
    = render(RatingComponent.new)
  div.bg-gray-100.rounded-sm.col-start-2.col-end-5.row-start-2.row-end-5
    = render(FieldComponent.new(game: @game))
  .h-full.overflow-y-scroll.bg-gray-100.rounded-sm.col-start-5.col-end-6.row-start-2.row-end-5
    = render(GameListComponent.new)
  div.bg-gray-100.rounded-sm.col-start-1.col-end-2.row-start-5.row-end-6.py-16
    | Copyright © #{Time.current.year}
    | &nbsp;
    span.tracking-wide.font-mono.text-lg nerve.ai
  div.bg-gray-100.rounded-sm.col-start-2.col-end-5.row-start-5.row-end-6
    = render(GameFormComponent.new(game_id: @game&.id))
  div.bg-gray-100.rounded-sm.col-start-5.col-end-6.row-start-5.row-end-6
    = render(GameComponent.new)